parameters:
  user.api.handler.class:  Lynx\ApiBundle\Handler\UserApiHandler
  user.api.class:  LynxBundle\Entity\User
services:  
  user.api.handler:
       class:        "%user.api.handler.class%"
       arguments:    ["@doctrine.orm.entity_manager", "%user.api.class%", "@form.factory"]  
  api_key_user_provider:
       class: Lynx\ApiBundle\Security\ApiKeyUserProvider  
       arguments:    ["@doctrine.orm.entity_manager"]  
  apikey_authenticator:
        class: Lynx\ApiBundle\Security\ApiKeyAuthenticator
        public: false     
