parameters:
  api.handler.class:  Lynx\ApiBundle\Handler\ApiHandler
  user.api.class:  LynxBundle\Entity\User
  user.api.type: Lynx\ApiBundle\Form\UserType
services:  
  user.api.handler:
       class:        "%api.handler.class%"
       arguments:    ["@doctrine.orm.entity_manager", "%user.api.class%", "@form.factory", "%user.api.type%", "@query_builder", "@api.respuestas"]  
  api_key_user_provider:
       class: Lynx\ApiBundle\Security\ApiKeyUserProvider  
       arguments:    ["@doctrine.orm.entity_manager"]  
  apikey_authenticator:
        class: Lynx\ApiBundle\Security\ApiKeyAuthenticator
        public: false  
  api.respuestas:
      class:        Lynx\ApiBundle\Services\RespuestasCabecera
  query_builder:
    class: Lynx\ApiBundle\Services\QueryBuilder
    arguments: ["@procesador_querystring", "@database_connection", "@validator"]
  procesador_querystring:
    class: Lynx\ApiBundle\Services\ProcesadorQuerystring
    arguments: ["@request_stack", "@validator"]
